name: Deploy master

on:
  workflow_dispatch:
    branches:
      - master

permissions:
  contents: write

jobs:
  build:
    name: Deploy 🚀
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions/setup-node@v2
        with:
          node-version: "18"
          cache: "npm"
      - run: npm i
      - run: npm run build
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
          single-commit: true
